# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinyl',
            name='format_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vinyl',
            name='isbn',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vinyl',
            name='label',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
